# This file was generated by jschema_to_python version 1.2.3.

import attr


@attr.s
class JobEvent(object):
    event_id = attr.ib(metadata={"schema_property_name": "EventId"})
    tenant_id = attr.ib(metadata={"schema_property_name": "TenantId"})
    timestamp = attr.ib(metadata={"schema_property_name": "Timestamp"})
    type = attr.ib(metadata={"schema_property_name": "Type"})
    job = attr.ib(default=None, metadata={"schema_property_name": "Job"})
    jobs = attr.ib(default=None, metadata={"schema_property_name": "Jobs"})
    organization_unit_id = attr.ib(default=None, metadata={"schema_property_name": "OrganizationUnitId"})
    start_info = attr.ib(default=None, metadata={"schema_property_name": "StartInfo"})
    user_id = attr.ib(default=None, metadata={"schema_property_name": "UserId"})
