# This file was generated by jschema_to_python_2 - lkekana version.

import attr


@attr.s
class JobEvent(object):
    EventId = attr.ib(metadata={"schema_property_name": "EventId"})
    TenantId = attr.ib(metadata={"schema_property_name": "TenantId"})
    Timestamp = attr.ib(metadata={"schema_property_name": "Timestamp"})
    Type = attr.ib(metadata={"schema_property_name": "Type"})
    Job = attr.ib(default=None, metadata={"schema_property_name": "Job"})
    Jobs = attr.ib(default=None, metadata={"schema_property_name": "Jobs"})
    OrganizationUnitId = attr.ib(default=None, metadata={"schema_property_name": "OrganizationUnitId"})
    StartInfo = attr.ib(default=None, metadata={"schema_property_name": "StartInfo"})
    UserId = attr.ib(default=None, metadata={"schema_property_name": "UserId"})


@attr.s
class Robot(object):
    Description = attr.ib(metadata={"schema_property_name": "Description"})
    HostingType = attr.ib(metadata={"schema_property_name": "HostingType"})
    Id = attr.ib(metadata={"schema_property_name": "Id"})
    MachineId = attr.ib(metadata={"schema_property_name": "MachineId"})
    MachineName = attr.ib(metadata={"schema_property_name": "MachineName"})
    Name = attr.ib(metadata={"schema_property_name": "Name"})
    Type = attr.ib(metadata={"schema_property_name": "Type"})
    UserName = attr.ib(metadata={"schema_property_name": "UserName"})
    Version = attr.ib(metadata={"schema_property_name": "Version"})

@attr.s
class Release(object):
    Description = attr.ib(metadata={"schema_property_name": "Description"})
    Id = attr.ib(metadata={"schema_property_name": "Id"})
    InputArguments = attr.ib(metadata={"schema_property_name": "InputArguments"})
    IsLatestVersion = attr.ib(metadata={"schema_property_name": "IsLatestVersion"})
    Key = attr.ib(metadata={"schema_property_name": "Key"})
    Name = attr.ib(metadata={"schema_property_name": "Name"})
    ProcessKey = attr.ib(metadata={"schema_property_name": "ProcessKey"})
    ProcessVersion = attr.ib(metadata={"schema_property_name": "ProcessVersion"})

@attr.s
class Job(object):
    Id = attr.ib(metadata={"schema_property_name": "Id"})
    Info = attr.ib(metadata={"schema_property_name": "Info"})
    Key = attr.ib(metadata={"schema_property_name": "Key"})
    OutputArguments = attr.ib(metadata={"schema_property_name": "OutputArguments"})
    Release = attr.ib(metadata={"schema_property_name": "Release"})
    Robot = attr.ib(metadata={"schema_property_name": "Robot"})
    StartTime = attr.ib(metadata={"schema_property_name": "StartTime"})
    State = attr.ib(metadata={"schema_property_name": "State"})

@attr.s
class StartInfo(object):
    JobsCount = attr.ib(metadata={"schema_property_name": "JobsCount"})
    ReleaseKey = attr.ib(metadata={"schema_property_name": "ReleaseKey"})
    Source = attr.ib(metadata={"schema_property_name": "Source"})
    Strategy = attr.ib(metadata={"schema_property_name": "Strategy"})
    RobotIds = attr.ib(factory=list, metadata={"schema_property_name": "RobotIds"})

@attr.s
class Jobs(object):
    BatchExecutionKey = attr.ib(metadata={"schema_property_name": "BatchExecutionKey"})
    Id = attr.ib(metadata={"schema_property_name": "Id"})
    InputArguments = attr.ib(metadata={"schema_property_name": "InputArguments"})
    Key = attr.ib(metadata={"schema_property_name": "Key"})
    OutputArguments = attr.ib(metadata={"schema_property_name": "OutputArguments"})
    Release = attr.ib(metadata={"schema_property_name": "Release"})
    ReleaseName = attr.ib(metadata={"schema_property_name": "ReleaseName"})
    Robot = attr.ib(metadata={"schema_property_name": "Robot"})
    Source = attr.ib(metadata={"schema_property_name": "Source"})
    SourceType = attr.ib(metadata={"schema_property_name": "SourceType"})
    State = attr.ib(metadata={"schema_property_name": "State"})
    Type = attr.ib(metadata={"schema_property_name": "Type"})
